workspace:
  base: /go
  path: src/github.com/SuperArnold/GO_Drone_Kubernetes

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  build_linux_amd64:
    image: golang:1.10
    group: build
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - make 

  deploy:
    image: sh4d1/drone-kubernetes
    kubernetes_template: deployment.yml
    kubernetes_namespace: default
    secrets: [ https://127.0.0.1:56919, LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeE1EUXdPVEU0TVRrME9Gb1hEVE14TURRd09ERTRNVGswT0Zvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHRQCnpoL3p4RDNzbmNUcm5JTi9tMGc3M2RyQ01mcWlrK1NTelhEZEtFRVlob3ZVNzJpbXhuNDFwR1hCMkgxOGhqUHEKcno5SU1VeEFodndFSE82UFJUWnRIWVorN0ZMdit5Y0EvbGt6OEpGQWJhNVNwd0pCejg3M3o3amtldXBuMmhoaQpiK2FxZWppOFZ2QmlvT3ROTm9rQlhvTkg2YU5Ca3k1ZDdQNzc3eHNNRUJTeVY0NEtaME1OcDJKUjh6QlAzM1ZRCk05MUFWQXRxNUVtT1hROUVtOUVLRmNaQXRvV1EyS2hJSW9HdkFHaEpQTlg0NGh0NisrMEdQaXRSbFhjMXNTbkUKQk5QcnZiRGVQNWVpaU5KMEY3OFRsRUwzYys2cEFzVjRpUmdmYm4xS0w0RC9McTJ0M0tIaGlrNTVCWlppQ0xqQgovQ2F2TnJ3V25sRVgwODRxNDZzQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJUV0pORS9BQU1uOGl6NzQ3MEVTczZFemhWYitqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFvR2gvM0g2TwpMd0EwL0IrdHFZcFFGRituVHJkcGF1NW1PTmUxRmlJVlNCdUQwNkJKTHM2MTErVVA1UFRxVG5yYzdQNkpaOTJ4CjIwaFljYVRvUE5kWHI3US81QWZPZWpRdGI5UWxqMGhra2o3WUwrRGZ6Vk5qK2dYN2V2VFRFZGIveHBOZVNNNDkKcXJBN1RSeDUzNzluK2E2SEMxa0dVUWRnbmNoWTEzVGJzYVVydmlLTVRVbzlMdlBRUFVXbUJua0l5bHZTZityRApLdmpoZ3RiZTFhTEk0MWh6WmVHV2JSWFYvY29wejdPQmtTQkpqMXNGYzJEVFVSQzJHY3dBWFN1LzBLeHBZcHpOCmNrYlp1NVlnaDNXT0pPdU5EanEwbnhSNGxxMkJuUXJqcis5VVhObFdBVEJNcDNzSGVtdmxreGI1OVIxWmhDOU4KTmlicmNXdkc2T3NXbnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==, eyJhbGciOiJSUzI1NiIsImtpZCI6Ik1YTHh6c0gxblZ2bTJ0U1RVRGw4Mnl5Q1gwM25keEpla3QzRlpxeEE3VncifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tc3NiazQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjhlMDE5NzY3LWFiOGUtNDdmMi1iNDljLThhMWZiZGM3YTE2OSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.a_NXS9povZ1jnOD5Ue-C693wIhkaJnC5IzwdMYTFxINMAJAonslzfEcRyFHVd8lSuWAxu0bFNuPUnsFp5ZA9S5sAYlSFL2UklqFUioNR6FnFBvIZvigEKLkDS5cJc7ITiBMR_Yx5ENr6_w2KFXdXsv7fpwgs3sBypgPDha3t9biXqhGAWuAeQnFXT_NjYUiprpF7lJMWcxIJcDs8Xti-UFqHz2wgVX0P_G90aOzesFpljmZdfagE3gCjoRmEMjqcMR_-aWkis7faELqm1dCfv2sezxrUOEi1RyItKrpIMRoewOZwODcIApnlwyCgobWwc_ktx1y_SRcAt-gjhu_mUg ]